In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)

Array: [1 2 3 4 5]


In [3]:
print("Data type:", arr1.dtype)
print("Shape:", arr1.shape) 
print("Size:", arr1.size)

Data type: int64
Shape: (5,)
Size: 5


In [4]:
arr=np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr = arr.reshape(1, 6)
print(arr.shape)
print(arr)

(6,)
(1, 6)
[[1 2 3 4 5 6]]


In [5]:
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)
print("Number of dimensions:", arr2.ndim)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


In [6]:
## Attributes of numpy arrays
# dtype: Data type of the array elements
# shape: Dimensions of the array
# size: Total number of elements in the array
# ndim: Number of dimensions (axes) of the array
# reshape: Change the shape of the array without changing its data
# flatten: Convert a multi-dimensional array into a 1D array
# arange: Create arrays with regularly spaced values
# linspace: Create arrays with a specified number of evenly spaced values over a specified interval
# zeros: Create an array filled with zeros
# ones: Create an array filled with ones
# eye: Create an identity matrix
# random: Generate arrays with random values
# concatenate: Join two or more arrays along an axis
# split: Split an array into multiple sub-arrays
# transpose: Swap the axes of an array
# dot: Perform matrix multiplication
# sum, mean, std, var: Statistical operations on arrays
# min, max: Find the minimum and maximum values in an array
# argmin, argmax: Find the indices of the minimum and maximum values in an array
# unique: Find the unique elements in an array
# sort: Sort the elements of an array
## Examples
import numpy as np
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Data type:", arr1.dtype)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Number of dimensions:", arr2.ndim)
# Reshaping an array
arr3 = np.array([1, 2, 3, 4, 5, 6])
print("\nOriginal Array:", arr3)
reshaped_arr = arr3.reshape(2, 3)
print("Reshaped Array (2x3):\n", reshaped_arr)
# Creating an array of zeros
zeros_arr = np.zeros((2, 3))
print("\nArray of Zeros (2x3):\n", zeros_arr)
# Creating an array of ones
ones_arr = np.ones((3, 2))
print("\nArray of Ones (3x2):\n", ones_arr)
# Creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix (3x3):\n", identity_matrix)
# Generating an array with random values
random_arr = np.random.rand(2, 3)
print("\nRandom Array (2x3):\n", random_arr)
# Concatenating two arrays
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr4, arr5))
print("\nConcatenated Array:", concatenated_arr)
# Splitting an array
split_arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(split_arr, 3)
print("\nSplit Arrays:", sub_arrays)
# Transposing an array
transposed_arr = arr2.T
print("\nTransposed Array:\n", transposed_arr)
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(mat1, mat2)
print("\nMatrix Product:\n", matrix_product)
# Statistical operations
stats_arr = np.array([1, 2, 3, 4, 5])
print("\nSum:", np.sum(stats_arr))
print("Mean:", np.mean(stats_arr))
print("Standard Deviation:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))
print("Min:", np.min(stats_arr))
print("Max:", np.max(stats_arr))
print("Index of Min:", np.argmin(stats_arr))
print("Index of Max:", np.argmax(stats_arr))
# Finding unique elements
unique_arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(unique_arr)
print("\nUnique Elements:", unique_elements)

1D Array: [1 2 3 4 5]
Data type: int64
Shape: (5,)
Size: 5

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Number of dimensions: 2

Original Array: [1 2 3 4 5 6]
Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]

Array of Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (2x3):
 [[0.507881   0.80777092 0.41748963]
 [0.11567628 0.32200785 0.4619723 ]]

Concatenated Array: [1 2 3 4 5 6]

Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]

Matrix Product:
 [[19 22]
 [43 50]]

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Index of Min: 0
Index of Max: 4

Unique Elements: [1 2 3 4 5]


In [7]:
## Numpy vectorization
import numpy as np
# Creating two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# Element-wise addition
sum_ab = a + b
print("Element-wise Addition:", sum_ab)
# Element-wise multiplication
prod_ab = a * b
print("Element-wise Multiplication:", prod_ab)
# Element-wise subtraction
diff_ab = a - b
print("Element-wise Subtraction:", diff_ab)
# Element-wise division
div_ab = a / b
print("Element-wise Division:", div_ab)
# Applying a mathematical function (e.g., square root)
sqrt_a = np.sqrt(a)
print("Square Root of a:", sqrt_a)
# Applying a mathematical function (e.g., exponential)
exp_b = np.exp(b)
print("Exponential of b:", exp_b)


Element-wise Addition: [ 6  8 10 12]
Element-wise Multiplication: [ 5 12 21 32]
Element-wise Subtraction: [-4 -4 -4 -4]
Element-wise Division: [0.2        0.33333333 0.42857143 0.5       ]
Square Root of a: [1.         1.41421356 1.73205081 2.        ]
Exponential of b: [ 148.4131591   403.42879349 1096.63315843 2980.95798704]


In [8]:
## Universal functions (ufuncs) in NumPy
import numpy as np
# Creating an array
arr = np.array([1, 4, 9, 16, 25])
# Applying the square root ufunc
sqrt_arr = np.sqrt(arr)
print("Square Roots:", sqrt_arr)
# Applying the exponential ufunc
exp_arr = np.exp(arr)
print("Exponentials:", exp_arr)


Square Roots: [1. 2. 3. 4. 5.]
Exponentials: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [9]:
## Sine and Cosine functions in NumPy
import numpy as np
# Creating an array of angles in radians
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
# Calculating the sine of the angles
sine_values = np.sin(angles)
print("Sine Values:", sine_values)
# Calculating the cosine of the angles
cosine_values = np.cos(angles)
print("Cosine Values:", cosine_values)


Sine Values: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
Cosine Values: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]


In [10]:
## Slicing and Indexing in NumPy
import numpy as np
# Creating a 1D array
arr1 = np.array([10, 20, 30, 40, 50])
# Slicing the array (elements from index 1 to 3)
slice1 = arr1[1:4]
print("Sliced Array (1 to 3):", slice1)
# Accessing a specific element (index 2)
element = arr1[2]
print("Element at Index 2:", element)
# Creating a 2D array
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# Slicing the array (first two rows and first two columns)
slice2 = arr2[0:2, 0:2]
print("Sliced 2D Array (first 2 rows and columns):\n", slice2)
# Accessing a specific element (row 1, column 2)
element2 = arr2[1, 2]
print("Element at Row 1, Column 2:", element2)
# Boolean indexing (elements greater than 30)
bool_index = arr1[arr1 > 30]
print("Elements Greater than 30:", bool_index)
# Fancy indexing (accessing specific indices)
fancy_index = arr1[[0, 2, 4]]
print("Fancy Indexed Elements (indices 0, 2, 4):", fancy_index)


Sliced Array (1 to 3): [20 30 40]
Element at Index 2: 30
Sliced 2D Array (first 2 rows and columns):
 [[10 20]
 [40 50]]
Element at Row 1, Column 2: 60
Elements Greater than 30: [40 50]
Fancy Indexed Elements (indices 0, 2, 4): [10 30 50]


In [11]:
## Statistical concepts -- Normalization
import numpy as np
# Creating an array
data = np.array([10, 20, 30, 40, 50])
# Min-Max Normalization
min_val = np.min(data)
max_val = np.max(data)
normalized_data = (data - min_val) / (max_val - min_val)
print("Min-Max Normalized Data:", normalized_data)
# Z-Score Normalization
mean_val = np.mean(data)
std_dev = np.std(data)
z_score_normalized_data = (data - mean_val) / std_dev
print("Z-Score Normalized Data:", z_score_normalized_data)
# Standardization
standardized_data = (data - mean_val) / std_dev
print("Standardized Data:", standardized_data)

Min-Max Normalized Data: [0.   0.25 0.5  0.75 1.  ]
Z-Score Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Standardized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
