In [17]:
import numpy as np

In [18]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)

Array: [1 2 3 4 5]


In [19]:
print("Data type:", arr1.dtype)
print("Shape:", arr1.shape) 
print("Size:", arr1.size)

Data type: int64
Shape: (5,)
Size: 5


In [20]:
arr=np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr = arr.reshape(1, 6)
print(arr.shape)
print(arr)

(6,)
(1, 6)
[[1 2 3 4 5 6]]


In [21]:
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)
print("Number of dimensions:", arr2.ndim)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


In [22]:
## Attributes of numpy arrays
# dtype: Data type of the array elements
# shape: Dimensions of the array
# size: Total number of elements in the array
# ndim: Number of dimensions (axes) of the array
# reshape: Change the shape of the array without changing its data
# flatten: Convert a multi-dimensional array into a 1D array
# arange: Create arrays with regularly spaced values
# linspace: Create arrays with a specified number of evenly spaced values over a specified interval
# zeros: Create an array filled with zeros
# ones: Create an array filled with ones
# eye: Create an identity matrix
# random: Generate arrays with random values
# concatenate: Join two or more arrays along an axis
# split: Split an array into multiple sub-arrays
# transpose: Swap the axes of an array
# dot: Perform matrix multiplication
# sum, mean, std, var: Statistical operations on arrays
# min, max: Find the minimum and maximum values in an array
# argmin, argmax: Find the indices of the minimum and maximum values in an array
# unique: Find the unique elements in an array
# sort: Sort the elements of an array
## Examples
import numpy as np
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Data type:", arr1.dtype)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Number of dimensions:", arr2.ndim)
# Reshaping an array
arr3 = np.array([1, 2, 3, 4, 5, 6])
print("\nOriginal Array:", arr3)
reshaped_arr = arr3.reshape(2, 3)
print("Reshaped Array (2x3):\n", reshaped_arr)
# Creating an array of zeros
zeros_arr = np.zeros((2, 3))
print("\nArray of Zeros (2x3):\n", zeros_arr)
# Creating an array of ones
ones_arr = np.ones((3, 2))
print("\nArray of Ones (3x2):\n", ones_arr)
# Creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix (3x3):\n", identity_matrix)
# Generating an array with random values
random_arr = np.random.rand(2, 3)
print("\nRandom Array (2x3):\n", random_arr)
# Concatenating two arrays
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr4, arr5))
print("\nConcatenated Array:", concatenated_arr)
# Splitting an array
split_arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(split_arr, 3)
print("\nSplit Arrays:", sub_arrays)
# Transposing an array
transposed_arr = arr2.T
print("\nTransposed Array:\n", transposed_arr)
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(mat1, mat2)
print("\nMatrix Product:\n", matrix_product)
# Statistical operations
stats_arr = np.array([1, 2, 3, 4, 5])
print("\nSum:", np.sum(stats_arr))
print("Mean:", np.mean(stats_arr))
print("Standard Deviation:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))
print("Min:", np.min(stats_arr))
print("Max:", np.max(stats_arr))
print("Index of Min:", np.argmin(stats_arr))
print("Index of Max:", np.argmax(stats_arr))
# Finding unique elements
unique_arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(unique_arr)
print("\nUnique Elements:", unique_elements)

1D Array: [1 2 3 4 5]
Data type: int64
Shape: (5,)
Size: 5

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Number of dimensions: 2

Original Array: [1 2 3 4 5 6]
Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]

Array of Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (2x3):
 [[0.4803505  0.18768998 0.46378894]
 [0.46310779 0.03029182 0.59395209]]

Concatenated Array: [1 2 3 4 5 6]

Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]

Matrix Product:
 [[19 22]
 [43 50]]

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Index of Min: 0
Index of Max: 4

Unique Elements: [1 2 3 4 5]


In [23]:
## Numpy vectorization
import numpy as np
# Creating two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# Element-wise addition
sum_ab = a + b
print("Element-wise Addition:", sum_ab)
# Element-wise multiplication
prod_ab = a * b
print("Element-wise Multiplication:", prod_ab)
# Element-wise subtraction
diff_ab = a - b
print("Element-wise Subtraction:", diff_ab)
# Element-wise division
div_ab = a / b
print("Element-wise Division:", div_ab)
# Applying a mathematical function (e.g., square root)
sqrt_a = np.sqrt(a)
print("Square Root of a:", sqrt_a)
# Applying a mathematical function (e.g., exponential)
exp_b = np.exp(b)
print("Exponential of b:", exp_b)


Element-wise Addition: [ 6  8 10 12]
Element-wise Multiplication: [ 5 12 21 32]
Element-wise Subtraction: [-4 -4 -4 -4]
Element-wise Division: [0.2        0.33333333 0.42857143 0.5       ]
Square Root of a: [1.         1.41421356 1.73205081 2.        ]
Exponential of b: [ 148.4131591   403.42879349 1096.63315843 2980.95798704]
